### ISSUE TITLE
Нормализовать структуру авторов

### ISSUE THREAD

**Issue by pepelsbey** [Y-Doka/content#352]
У нас сейчас кто-то в строку, кто-то списком, кто-то в единственном числе, кто-то во множественном.

Хорошо бы вот так:

```yml
authors:
  - username
contributors:
  - username
  - username
  - username
editors:
  - username
```

Это сразу допускает, что может быть больше одного автора и больше одного редактора.

Аналогично я бы заложился в шаблонах, чтобы вывод работал с массивом, даже если там всего один пункт.
