### ISSUE TITLE
Отрефакторить листинги CSS-свойств

### ISSUE THREAD

**Issue by pepelsbey** [Y-Doka/content#783]
Чтобы это был настоящий CSS с селектором и чтобы текст был текстом, а не комментарием в блоке кода. В таком стиле я стараюсь двигаться в ревью и надо бы отрефакторить существующие статьи.

@solarrust так ведь? :)

# Было

```css
/* Ключевые слова */
transform: none;

/* Функции в качестве значения */
transform: matrix(1, 2, 3, 4, 5, 6);
transform: matrix3d(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1);

/* Глобальные значения */
transform: inherit;
transform: initial;
transform: unset;
```

# Стало

Ключевые слова:

```css
.element {
  transform: none;
}
```

Функции в качестве значения:

```css
.element {
  transform: matrix(1, 2, 3, 4, 5, 6);
  transform: matrix3d(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1);
}
```

Глобальные значения:

```css
.element {
  transform: inherit;
  transform: initial;
  transform: unset;
}
```
